### ISSUE TITLE
Regarding the link 

### ISSUE THREAD

**Issue by anujn08** [sharad1126/ccat#1]
https://sharad1126.github.io/projects/cdr.html
 Kindly help me out with this. Unable to reach the link and explore more on this topic. Please provide mail id to reach out.

**Comment by sharad1126** [comment]
> https://sharad1126.github.io/projects/cdr.html Kindly help me out with this. Unable to reach the link and explore more on this topic. Please provide mail id to reach out.

Hi @anujn08, yes, the link was taken down a long time ago as the website was revamped. Please tell more about yourself and what you aim to get from this project. The repository has all code that's required.
